version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: carsales-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "car-sales-db"
